# Generated by Django 6.0.3 on 2026-09-03 20:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPurchasePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tokens', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_cents', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_cents'],
            },
        ),
        migrations.CreateModel(
            name='AIServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_highlighting_enabled', models.BooleanField(default=True)),
                ('ai_marking_enabled', models.BooleanField(default=True)),
                ('ai_research_guidance_enabled', models.BooleanField(default=True)),
                ('token_cost_cents', models.PositiveIntegerField(default=1, help_text='Cost per AI token consumed, in cents.', validators=[django.core.validators.MinValueValidator(1)])),
                ('free_tokens_per_month', models.PositiveIntegerField(default=1000, help_text='Number of AI tokens a user can consume for free each month.')),
                ('allow_pay_as_you_go', models.BooleanField(default=True)),
                ('max_purchasable_tokens', models.PositiveIntegerField(blank=True, help_text='Optional cap on total purchasable tokens per cycle. Null = unlimited.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Service Configuration',
                'verbose_name_plural': 'AI Service Configuration',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. "CS301".', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('STRUCTURED', 'Structured (Essay/Long Answer)')], db_index=True, max_length=20)),
                ('text', models.TextField(help_text='The question prompt shown to the student.')),
                ('options', models.JSONField(blank=True, help_text='List of choice strings, e.g. ["A", "B", "C", "D"]. Required for MCQ, must be null otherwise.', null=True)),
                ('correct_option', models.PositiveIntegerField(blank=True, help_text='0-based index into `options` identifying the correct choice. Required for MCQ.', null=True)),
                ('marks', models.PositiveIntegerField(default=1, help_text='Default marks awarded for a fully correct answer.', validators=[django.core.validators.MinValueValidator(1)])),
                ('explanation', models.TextField(blank=True, help_text='Optional explanation shown after grading, for either question type.')),
                ('model_answer', models.TextField(blank=True, help_text='Reference answer used as grading context for AI evaluation.')),
                ('rubric', models.JSONField(blank=True, help_text='List of {criterion, max_points, description} used for structured-answer grading.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('LECTURER', 'Lecturer'), ('ADMIN', 'Administrator')], db_index=True, default='STUDENT', help_text='Which portal/permission set this account uses.', max_length=20)),
                ('email', models.EmailField(help_text='Used for login/notifications; must be unique across all accounts.', max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('NOTE', 'Note'), ('QUESTION_BANK', 'Question Bank'), ('SOLUTION_BANK', 'Solution Bank'), ('RESEARCH', 'Research'), ('PROPOSAL', 'Proposal'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private (only uploader)'), ('COURSE', 'Course (enrolled students)'), ('PUBLIC', 'Public (all authenticated users)')], db_index=True, default='COURSE', max_length=20)),
                ('content_text', models.TextField(blank=True, help_text='Extracted plain text, used for search and AI features.')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Precomputed Postgres tsvector; do not set manually — see sync_document_search_vector.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text="Optional — some documents (e.g. general research) aren't tied to one course.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='campusos.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_time', models.DateTimeField(blank=True, db_index=True, help_text='Optional scheduled start; null means available anytime.', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Optional scheduled end.', null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Unpublished exams are hidden from students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='campusos.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, help_text="1 for a student's first attempt at this exam, 2 for a retake, etc.")),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, help_text='Set when the attempt is submitted or times out.', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Total score after grading; null until graded.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='campusos.exam')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('text', models.TextField(help_text='Snapshot of the highlighted text itself, for display without re-slicing content_text.')),
                ('note', models.TextField(blank=True, help_text="User's own annotation/comment on this highlight.")),
                ('color', models.CharField(default='yellow', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='campusos.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_offset'],
            },
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Institution-issued staff number.', max_length=20, unique=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('designation', models.CharField(blank=True, help_text='e.g. "Senior Lecturer", "Professor".', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(help_text='Primary instructor. Nullable so course history survives lecturer deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='campusos.lecturerprofile'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('tokens_purchased', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text="Payment gateway reference ID. Unique so retried webhooks can't double-process a payment.", max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='PROTECT: payment records must be retained for accounting/compliance even if the account is later removed.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Display/attempt order within the exam.')),
                ('marks', models.PositiveIntegerField(blank=True, help_text="Override Question.marks for this exam specifically. Null = use the question's default.", null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='campusos.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_links', to='campusos.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(help_text='Use ExamQuestion to add questions — controls order and mark overrides.', related_name='exams', through='campusos.ExamQuestion', to='campusos.question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.PositiveIntegerField(blank=True, help_text="Index into the question's options. MCQ only.", null=True)),
                ('answer_text', models.TextField(blank=True, help_text='Free-text answer. Structured questions only.')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True, help_text='Human or AI-generated feedback on this specific answer.')),
                ('ai_evaluation', models.JSONField(blank=True, help_text='Raw AI grading output, e.g. per-criterion scores/rationale.', null=True)),
                ('is_correct', models.BooleanField(blank=True, help_text='MCQ only; null for structured answers.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='campusos.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='campusos.question')),
            ],
            options={
                'ordering': ['question_id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='campusos.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='campusos.questionbank'),
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(help_text='List of {name, description, weight} defining how scores are computed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Optional — a rubric can be course-specific or reused across courses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubrics', to='campusos.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_status', models.CharField(choices=[('PENDING', 'Pending Evaluation'), ('EVALUATED', 'Evaluated'), ('REVIEWED', 'Reviewed by Lecturer')], db_index=True, default='PENDING', max_length=20)),
                ('ai_feedback', models.JSONField(blank=True, help_text='Cache of latest RubricEvaluation.feedback — see class docstring.', null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Cache of latest RubricEvaluation.overall_score — see class docstring.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lecturer_comments', models.TextField(blank=True, help_text='Optional human override/commentary on top of the AI evaluation.')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_submissions', to='campusos.course')),
                ('document', models.OneToOneField(help_text='The uploaded paper/proposal file backing this submission.', on_delete=django.db.models.deletion.CASCADE, related_name='research_submission', to='campusos.document')),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campusos.rubric')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(help_text='Per-criterion scores, keyed to match Rubric.criteria.')),
                ('feedback', models.JSONField(help_text='Per-criterion feedback text.')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campusos.rubric')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='campusos.researchsubmission')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Institution-issued student number.', max_length=20, unique=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('enrollment_year', models.PositiveIntegerField(blank=True, help_text='Calendar year the student enrolled, e.g. 2024.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('user', models.OneToOneField(help_text='The underlying auth account. Deleting the user deletes this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='researchsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_submissions', to='campusos.studentprofile'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='campusos.studentprofile'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, db_index=True, help_text='e.g. "2024-Fall".', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='campusos.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='campusos.studentprofile')),
            ],
            options={
                'ordering': ['course__code'],
            },
        ),
        migrations.CreateModel(
            name='UserAICredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_tokens', models.IntegerField(default=0, help_text='Current available AI tokens. Never allowed to go negative.', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_purchased_tokens', models.PositiveIntegerField(default=0, help_text='Lifetime total of tokens purchased, for analytics.')),
                ('last_reset_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the free monthly allowance was last reset.')),
                ('user', models.OneToOneField(help_text='The user whose balance is tracked here.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, help_text="'highlight', 'marking', 'research_guidance', etc.", max_length=50)),
                ('tokens_used', models.PositiveIntegerField()),
                ('cost_cents', models.PositiveIntegerField(help_text='Monetary cost at time of use, denormalized from AIServiceConfig for historical accuracy.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_answer', models.ForeignKey(blank=True, help_text='The answer this AI call graded, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='campusos.answer')),
                ('related_document', models.ForeignKey(blank=True, help_text='The document this AI call operated on, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='campusos.document')),
                ('user', models.ForeignKey(help_text='PROTECT: usage history is a billing record and must survive user-deletion attempts.', on_delete=django.db.models.deletion.PROTECT, related_name='ai_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['course', 'category'], name='campusos_do_course__070aea_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='campusos_do_uploade_9c2bed_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['course', 'visibility', 'category'], name='campusos_do_course__b93a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='doc_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['document', 'start_offset'], name='campusos_hi_documen_5ebbc3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'code'], name='campusos_co_departm_fe8af7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', '-created_at'], name='campusos_pa_user_id_4dcc80_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='campusos_pa_status_127da7_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'order'], name='campusos_ex_exam_id_8926e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('exam', 'question')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'is_published'], name='campusos_ex_course__911007_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_published', 'start_time'], name='campusos_ex_is_publ_9271b3_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'is_correct'], name='campusos_an_questio_773067_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['course', '-created_at'], name='campusos_qu_course__128ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['bank', 'question_type'], name='campusos_qu_bank_id_d39d18_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricevaluation',
            index=models.Index(fields=['submission', '-evaluated_at'], name='campusos_ru_submiss_dda9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsubmission',
            index=models.Index(fields=['student', 'evaluation_status'], name='campusos_re_student_bd694e_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsubmission',
            index=models.Index(fields=['course', 'evaluation_status'], name='campusos_re_course__6d1547_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'status'], name='campusos_ex_student_90de17_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'status'], name='campusos_ex_exam_id_3e1222_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('exam', 'student'), name='one_in_progress_attempt_per_student'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('exam', 'student', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'semester'], name='campusos_en_course__93444b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'semester')},
        ),
        migrations.AddIndex(
            model_name='useraiusage',
            index=models.Index(fields=['user', '-created_at'], name='campusos_us_user_id_02e57d_idx'),
        ),
        migrations.AddIndex(
            model_name='useraiusage',
            index=models.Index(fields=['feature', '-created_at'], name='campusos_us_feature_07a7cd_idx'),
        ),
    ]
